// Code generated by protoc-gen-go from "protodb/records_test.proto"
// DO NOT EDIT!

package protodb

import proto "code.google.com/p/goprotobuf/proto"
import "math"

// Reference proto and math imports to suppress error if they are not otherwise used.
var _ = proto.GetString
var _ = math.Inf

type TestRecord struct {
	Key              *TestRecord_Key `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Val              *string         `protobuf:"bytes,2,req,name=val" json:"val,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *TestRecord) Reset()         { *this = TestRecord{} }
func (this *TestRecord) String() string { return proto.CompactTextString(this) }

type TestRecord_Key struct {
	Val              *string `protobuf:"bytes,1,req,name=val" json:"val,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *TestRecord_Key) Reset()         { *this = TestRecord_Key{} }
func (this *TestRecord_Key) String() string { return proto.CompactTextString(this) }

type NumberedTestRecord struct {
	Key              *uint32 `protobuf:"fixed32,1,opt,name=key" json:"key,omitempty"`
	Val              *string `protobuf:"bytes,2,req,name=val" json:"val,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *NumberedTestRecord) Reset()         { *this = NumberedTestRecord{} }
func (this *NumberedTestRecord) String() string { return proto.CompactTextString(this) }

func init() {
}
